name: Gerar Cobrinha ğŸ

on:
  schedule:
    - cron: "0 */12 * * *"  # Atualiza a cada 12 horas
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o repositÃ³rio
        uses: actions/checkout@v3

      - name: Gerar animaÃ§Ã£o da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: JoaoGSantiago
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Enviar mudanÃ§as
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualizando cobrinha ğŸ"
          add: "github-contribution-grid-snake.svg github-contribution-grid-snake-dark.svg"
